name: CI Pipeline

# This workflow is intentionally incomplete. Read it, change it, and extend it.

on:
  push:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: xUnit install
        run: dotnet new install xunit.v3.templates

      - name: Restore dependencies
        run: cd csharp && dotnet restore

      - name: Build project
        run: cd csharp && dotnet build --no-restore --configuration Release -warnaserror # warnaserror: Treat warnings as errors
      
      - name: Test
        run: cd csharp && dotnet test --verbosity normal

